name: Deploy app_1

on: workflow_dispatch

jobs:
  some-work:
    runs-on: ubuntu-latest
    steps:
    - name: Setup gcloud Production
      uses: google-github-actions/setup-gcloud@v0
      with:
          version: '306.0.0'
          project_id: dhh---analytics-apac
          service_account_key: ${{ secrets.MY_SECRET }}
          export_default_credentials: true