name: Deploy app_1

on: workflow_dispatch

jobs:
  some-work:
    runs-on: ubuntu-latest
    steps:
    - name: Print Environment Args
      run: |
        echo "Environment Args:"
        echo "Service Account Key"

    outputs:
      saKey: MY_SECRET

  call-workflow-passing-data:
    needs: some-work
    uses: ./.github/workflows/reusable.yaml
    with:
      username: app_1_username
      some_flag: true
    secrets:
      token: ${{ secrets[format('{0}', needs.some-work.outputs.saKey)] }}