name: Deploy app_1

on: workflow_dispatch

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable.yaml
    with:
      username: app_1_username
      some_flag: true
    secrets:
      token: mysecrettokenhere