name: Deploy app_1

on: workflow_dispatch

jobs:
  spin_up:
    name: spin_up
    runs-on: ubuntu-latest
    env:
      service-account-key: blah

    - name: Print Environment Args
      run: |
        echo "Environment Args:"
        echo "Service Account Key: ${{env.service-account-key}}"

    outputs:
      saKey: ${{env.service-account-key}

  call-workflow-passing-data:
    uses: ./.github/workflows/reusable.yaml
    with:
      username: app_1_username
      some_flag: true
    secrets:
      token: ${{ secrets.MY_SECRET }}