name: Deploy app_2

on: 
  workflow_dispatch:
    inputs:
      some_flag:
        type: boolean
        description: Some Flag
      username:
        type: string
        description: Username

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable.yaml
    with:
      username: app_2_username
      some_flag: false
