name: Deploy app_1

on:
  workflow_dispatch:
    inputs:
      appKey:
        type: choice
        description: 'Which app? (https://github.com/deliveryhero/pandata-ml-env/blob/master/deploy_vars.yaml)'
        required: true
        options:
        - demo_bq_access
        - menu_ranking_weighted_sum
        - competitor_data_mapping

jobs:
  some-work:
    runs-on: ubuntu-latest
    env:
      ENVVAR: MY_SECRET
    steps:
    - name: Print Environment Args
      run: |
        echo "Environment Args:"
        echo "Service Account Key"

    outputs:
      saKey: MY_SECRET

  call-workflow-passing-data:
    needs: some-work
    uses: ./.github/workflows/reusable.yaml
    with:
      username: app_1_username
      some_flag: true
    secrets:
      token: ${{ secrets[format('{0}', needs.some-work.outputs.saKey)] }}