name: Reusable workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

      some_flag:
        required: true
        type: boolean

jobs:
  reusable_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}

      - name: Print inputs
        run: |
          echo "--- Printing inputs ---"
          echo "${{ inputs.username }}"
          echo "${{ inputs.some_flag }}"

      - name: Print secrets
        run: |
          echo "--- Printing secret ---"
          echo $MY_SECRET
          echo "---done"

