name: Reusable workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

      some_flag:
        required: true
        type: boolean

    secrets:
      token:
        required: true

jobs:
  reusable_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "--- Printing inputs ---"
          echo "${{ inputs.username }}"
          echo "${{ inputs.some_flag }}"

      - name: Print secrets
        run: |
          echo "secret:"
          echo ${{ secrets.token }}

      - name: Setup gcloud Production
        uses: google-github-actions/setup-gcloud@v0
        with:
            version: '306.0.0'
            project_id: dhh---analytics-apac
            service_account_key: ${{ secrets.token }}
            export_default_credentials: true
